*** Starting uWSGI 2.0.10 (64bit) on [Wed Sep  9 16:07:00 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8030 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x26d3860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
Traceback (most recent call last):
  File "./django_uwsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressor
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 4047, cores: 1)
spawned uWSGI worker 2 (pid: 4057, cores: 1)
spawned uWSGI worker 3 (pid: 4058, cores: 1)
spawned uWSGI worker 4 (pid: 4059, cores: 1)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 09:52:29 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8030 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f84860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
Traceback (most recent call last):
  File "./django_uwsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressor
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 6137, cores: 1)
spawned uWSGI worker 2 (pid: 6147, cores: 1)
spawned uWSGI worker 3 (pid: 6148, cores: 1)
spawned uWSGI worker 4 (pid: 6149, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/1] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:52:30 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/2] 192.168.1.108 () {46 vars in 738 bytes} [Thu Sep 10 09:52:31 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/3] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:52:32 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/4] 192.168.1.108 () {46 vars in 738 bytes} [Thu Sep 10 09:52:32 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/5] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:53:11 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/6] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:53:11 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/7] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:53:12 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/8] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:53:12 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/9] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:53:12 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/10] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:53:12 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/11] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:53:17 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/12] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:53:17 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/13] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:53:36 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/14] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:53:36 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/15] 192.168.1.108 () {44 vars in 763 bytes} [Thu Sep 10 09:55:42 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6147|app: -1|req: -1/16] 192.168.1.108 () {42 vars in 685 bytes} [Thu Sep 10 09:55:42 2015] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 11:10:12 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8030 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x225c860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
Traceback (most recent call last):
  File "./django_uwsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressor
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 3568, cores: 1)
spawned uWSGI worker 2 (pid: 3578, cores: 1)
spawned uWSGI worker 3 (pid: 3579, cores: 1)
spawned uWSGI worker 4 (pid: 3580, cores: 1)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 11:53:06 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8030).
bind(): Address already in use [core/socket.c line 764]
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 11:54:38 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8030 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2713860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2713860 pid: 4310 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 4310, cores: 1)
spawned uWSGI worker 2 (pid: 4320, cores: 1)
spawned uWSGI worker 3 (pid: 4321, cores: 1)
spawned uWSGI worker 4 (pid: 4322, cores: 1)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 12:03:27 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1256860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1256860 pid: 4451 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 4451, cores: 1)
spawned uWSGI worker 2 (pid: 4461, cores: 1)
spawned uWSGI worker 3 (pid: 4462, cores: 1)
spawned uWSGI worker 4 (pid: 4463, cores: 1)
/home/develop/static
[pid: 4461|app: 0|req: 1/1] 192.168.1.108 () {46 vars in 785 bytes} [Thu Sep 10 12:04:26 2015] GET / => generated 15864 bytes in 356 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 2/2] 192.168.1.108 () {52 vars in 936 bytes} [Thu Sep 10 12:04:36 2015] POST /account/check_phone => generated 18 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 3/3] 192.168.1.108 () {52 vars in 928 bytes} [Thu Sep 10 12:04:40 2015] POST /account/u_login => generated 15 bytes in 283 msecs (HTTP/1.1 200) 4 headers in 230 bytes (1 switches on core 0)
/home/develop/static
[pid: 4451|app: 0|req: 1/4] 192.168.1.108 () {48 vars in 866 bytes} [Thu Sep 10 12:04:41 2015] GET /shop/home => generated 19452 bytes in 170 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/home/develop/static
[pid: 4461|app: 0|req: 4/5] 192.168.1.108 () {54 vars in 985 bytes} [Thu Sep 10 12:04:41 2015] POST /account/u_login => generated 15 bytes in 215 msecs (HTTP/1.1 200) 4 headers in 230 bytes (1 switches on core 0)
[pid: 4463|app: 0|req: 1/6] 192.168.1.108 () {54 vars in 985 bytes} [Thu Sep 10 12:04:41 2015] POST /account/u_login => generated 15 bytes in 210 msecs (HTTP/1.1 200) 4 headers in 230 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 5/7] 192.168.1.108 () {48 vars in 875 bytes} [Thu Sep 10 12:04:42 2015] GET /shop/home => generated 19452 bytes in 29 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 6/8] 192.168.1.108 () {48 vars in 912 bytes} [Thu Sep 10 12:04:47 2015] GET /shop/goods-detail?goods_id=7 => generated 17973 bytes in 85 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 7/9] 192.168.1.108 () {48 vars in 955 bytes} [Thu Sep 10 12:04:49 2015] GET /designer/designer_personal?designer_id=1 => generated 12860 bytes in 28 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 8/10] 192.168.1.108 () {54 vars in 1031 bytes} [Thu Sep 10 12:04:51 2015] POST /designer/sort_list => generated 1473 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 9/11] 192.168.1.108 () {54 vars in 1031 bytes} [Thu Sep 10 12:04:52 2015] POST /designer/sort_list => generated 1473 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 10/12] 192.168.1.108 () {54 vars in 1031 bytes} [Thu Sep 10 12:04:52 2015] POST /designer/sort_list => generated 1473 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 11/13] 192.168.1.108 () {48 vars in 943 bytes} [Thu Sep 10 12:04:57 2015] GET /shop/goods-detail?goods_id=6 => generated 17857 bytes in 95 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 12/14] 192.168.1.108 () {54 vars in 1013 bytes} [Thu Sep 10 12:04:59 2015] POST /shop/mark-goods => generated 20 bytes in 112 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Vender_Goods.collected_time received a naive datetime (2015-09-10 12:05:00.471488) while time zone support is active.
  RuntimeWarning)

[pid: 4461|app: 0|req: 13/15] 192.168.1.108 () {54 vars in 1013 bytes} [Thu Sep 10 12:05:00 2015] POST /shop/mark-goods => generated 20 bytes in 151 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
3 /static/54bf9d0d40c98280a0bab10ce3fb993b.stl
http://www.3dilove.com/stl_static/54bf9d0d40c98280a0bab10ce3fb993b.stl
[pid: 4461|app: 0|req: 14/16] 192.168.1.108 () {54 vars in 1015 bytes} [Thu Sep 10 12:05:02 2015] POST /designer/show_3d => generated 86 bytes in 77 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 15/17] 192.168.1.108 () {48 vars in 912 bytes} [Thu Sep 10 12:17:40 2015] GET /shop/goods-detail?goods_id=7 => generated 17973 bytes in 95 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 16/18] 192.168.1.108 () {50 vars in 906 bytes} [Thu Sep 10 12:20:20 2015] GET /shop/home => generated 19452 bytes in 25 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4461|app: 0|req: 17/19] 192.168.1.108 () {48 vars in 912 bytes} [Thu Sep 10 12:20:21 2015] GET /shop/goods-detail?goods_id=5 => generated 17966 bytes in 101 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
3 /static/59bfd639738b706bb10eecdd800195ea.stl
http://www.3dilove.com/stl_static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 4461|app: 0|req: 18/20] 192.168.1.108 () {54 vars in 1015 bytes} [Thu Sep 10 12:20:26 2015] POST /designer/show_3d => generated 86 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 12:20:52 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8077).
bind(): Address already in use [core/socket.c line 764]
[pid: 4461|app: 0|req: 19/21] 192.168.1.108 () {50 vars in 943 bytes} [Thu Sep 10 12:20:53 2015] GET /shop/goods-detail?goods_id=5 => generated 17966 bytes in 69 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
http://www.3dilove.com/stl_static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 4461|app: 0|req: 20/22] 192.168.1.108 () {54 vars in 1015 bytes} [Thu Sep 10 12:20:55 2015] POST /designer/show_3d => generated 86 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Thu Sep 10 12:34:06 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16d3860
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291040 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
127.0.1.1
in test server
/home/develop/static
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16d3860 pid: 5052 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 5052, cores: 1)
spawned uWSGI worker 2 (pid: 5062, cores: 1)
spawned uWSGI worker 3 (pid: 5063, cores: 1)
spawned uWSGI worker 4 (pid: 5064, cores: 1)
/home/develop/static
[pid: 5062|app: 0|req: 1/1] 192.168.1.108 () {46 vars in 811 bytes} [Thu Sep 10 12:34:11 2015] GET / => generated 19452 bytes in 94 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 2/2] 192.168.1.108 () {48 vars in 893 bytes} [Thu Sep 10 12:34:13 2015] GET /goods-detail?goods_id=7 => generated 2707 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Fri Sep 11 09:43:22 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8077).
bind(): Address already in use [core/socket.c line 764]
[pid: 5062|app: 0|req: 3/3] 192.168.1.108 () {44 vars in 754 bytes} [Fri Sep 11 09:43:37 2015] GET / => generated 15864 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 4/4] 192.168.1.108 () {52 vars in 936 bytes} [Fri Sep 11 09:43:43 2015] POST /account/check_phone => generated 18 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 5/5] 192.168.1.108 () {52 vars in 928 bytes} [Fri Sep 11 09:43:46 2015] POST /account/u_login => generated 15 bytes in 352 msecs (HTTP/1.1 200) 4 headers in 230 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 6/6] 192.168.1.108 () {48 vars in 866 bytes} [Fri Sep 11 09:43:46 2015] GET /shop/home => generated 19525 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 7/7] 192.168.1.108 () {48 vars in 912 bytes} [Fri Sep 11 09:43:50 2015] GET /shop/goods-detail?goods_id=5 => generated 18001 bytes in 162 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 8/8] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 09:43:51 2015] POST /designer/show_3d => generated 60 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 9/9] 192.168.1.108 () {50 vars in 943 bytes} [Fri Sep 11 09:44:58 2015] GET /shop/goods-detail?goods_id=5 => generated 18001 bytes in 90 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
3 /static/59bfd639738b706bb10eecdd800195ea.stl
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 10/10] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 09:45:00 2015] POST /designer/show_3d => generated 60 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 11/11] 192.168.1.108 () {50 vars in 943 bytes} [Fri Sep 11 09:45:09 2015] GET /shop/goods-detail?goods_id=5 => generated 18001 bytes in 66 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 12/12] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 09:45:12 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Fri Sep 11 10:55:30 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8077).
bind(): Address already in use [core/socket.c line 764]
[pid: 5062|app: 0|req: 13/13] 192.168.1.108 () {44 vars in 754 bytes} [Fri Sep 11 10:55:39 2015] GET / => generated 15864 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 14/14] 192.168.1.108 () {46 vars in 809 bytes} [Fri Sep 11 10:55:42 2015] GET /shop/home => generated 19480 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 15/15] 192.168.1.108 () {52 vars in 945 bytes} [Fri Sep 11 10:55:48 2015] POST /account/check_phone => generated 18 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 16/16] 192.168.1.108 () {52 vars in 937 bytes} [Fri Sep 11 10:55:50 2015] POST /account/u_login => generated 15 bytes in 228 msecs (HTTP/1.1 200) 4 headers in 230 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 17/17] 192.168.1.108 () {50 vars in 906 bytes} [Fri Sep 11 10:55:50 2015] GET /shop/home => generated 19514 bytes in 27 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 18/18] 192.168.1.108 () {48 vars in 891 bytes} [Fri Sep 11 10:55:51 2015] GET /designer/my_state => generated 7139 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:52.642665) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/home/develop/static
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:53.050107) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 19/19] 192.168.1.108 () {52 vars in 893 bytes} [Fri Sep 11 10:55:52 2015] POST /designer/works_visit => generated 314 bytes in 444 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5063|app: 0|req: 1/20] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:53 2015] GET /designer/my_state => generated 7139 bytes in 97 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:53.334152) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:53.751506) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 20/21] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:53 2015] POST /designer/works_visit => generated 314 bytes in 450 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 21/22] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:54 2015] GET /designer/my_state => generated 7139 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:54.781753) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:55.185086) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 22/23] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:54 2015] POST /designer/works_visit => generated 314 bytes in 437 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 23/24] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:55 2015] GET /designer/my_state => generated 7139 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:56.100704) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:56.505169) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 24/25] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:56 2015] POST /designer/works_visit => generated 314 bytes in 439 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/home/develop/static
[pid: 5064|app: 0|req: 1/26] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:56 2015] GET /designer/my_state => generated 7139 bytes in 84 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:56.934051) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:57.309084) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 25/27] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:56 2015] POST /designer/works_visit => generated 314 bytes in 410 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 26/28] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:57 2015] GET /designer/my_state => generated 7139 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:57.674499) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:58.081799) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 27/29] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:57 2015] POST /designer/works_visit => generated 314 bytes in 441 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/home/develop/static
[pid: 5052|app: 0|req: 1/30] 192.168.1.108 () {50 vars in 922 bytes} [Fri Sep 11 10:55:58 2015] GET /designer/my_state => generated 7139 bytes in 78 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-10 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-09 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-08 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-07 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-06 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-05 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-04 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-03 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-02 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-09-01 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-31 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-30 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-29 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-28 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-27 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-26 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-25 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-24 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-23 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-22 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-21 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-20 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-19 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-18 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-17 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-16 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-15 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-14 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-13 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Good_record.g_visit_time received a naive datetime (2015-08-12 11:55:58.483636) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-10 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-09 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-08 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-07 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-06 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-05 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-04 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-03 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-02 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-09-01 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-31 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-30 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-29 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-28 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-27 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-26 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-25 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-24 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-23 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-22 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-21 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-20 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-19 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-18 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-17 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-16 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-15 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-14 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-13 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Design_record.d_visit_time received a naive datetime (2015-08-12 11:55:58.892006) while time zone support is active.
  RuntimeWarning)

[pid: 5062|app: 0|req: 28/31] 192.168.1.108 () {54 vars in 924 bytes} [Fri Sep 11 10:55:58 2015] POST /designer/works_visit => generated 314 bytes in 440 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 29/32] 192.168.1.108 () {48 vars in 911 bytes} [Fri Sep 11 10:55:59 2015] GET /designer/designer_works => generated 11276 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 30/33] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 10:56:00 2015] POST /designer/workd_unexecute => generated 1844 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 31/34] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 10:56:02 2015] POST /designer/auditing => generated 5295 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 32/35] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 10:56:03 2015] POST /designer/workd_unexecute => generated 1844 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
3 /static/aa80862af2ad46fb9cfdf06cf640df2e.stl
/static/aa80862af2ad46fb9cfdf06cf640df2e.stl
[pid: 5062|app: 0|req: 33/36] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 10:56:05 2015] POST /designer/show_3d => generated 60 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 34/37] 192.168.1.108 () {50 vars in 942 bytes} [Fri Sep 11 10:58:07 2015] GET /designer/designer_works => generated 11276 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 35/38] 192.168.1.108 () {56 vars in 1055 bytes} [Fri Sep 11 10:58:07 2015] POST /designer/workd_unexecute => generated 1844 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/aa80862af2ad46fb9cfdf06cf640df2e.stl
[pid: 5062|app: 0|req: 36/39] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 10:58:09 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 37/40] 192.168.1.108 () {50 vars in 942 bytes} [Fri Sep 11 10:58:14 2015] GET /designer/designer_works => generated 11276 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 38/41] 192.168.1.108 () {56 vars in 1055 bytes} [Fri Sep 11 10:58:15 2015] POST /designer/workd_unexecute => generated 1844 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/aa80862af2ad46fb9cfdf06cf640df2e.stl
[pid: 5062|app: 0|req: 39/42] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 10:58:17 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 2/43] 192.168.1.108 () {50 vars in 942 bytes} [Fri Sep 11 11:00:01 2015] GET /designer/designer_works => generated 11276 bytes in 18 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 3/44] 192.168.1.108 () {56 vars in 1055 bytes} [Fri Sep 11 11:00:01 2015] POST /designer/workd_unexecute => generated 1844 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/aa80862af2ad46fb9cfdf06cf640df2e.stl
[pid: 5062|app: 0|req: 40/45] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:00:04 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 41/46] 192.168.1.108 () {54 vars in 1016 bytes} [Fri Sep 11 11:00:17 2015] POST /designer/screenshot => generated 10944 bytes in 41 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Goods_Upload.restdate received a naive datetime (2015-09-16 11:00:17.319586) while time zone support is active.
  RuntimeWarning)

[pid: 5064|app: 0|req: 4/47] 192.168.1.108 () {56 vars in 1162 bytes} [Fri Sep 11 11:00:17 2015] POST /designer/edit_submit => generated 0 bytes in 113 msecs (HTTP/1.1 302) 4 headers in 161 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 42/48] 192.168.1.108 () {50 vars in 948 bytes} [Fri Sep 11 11:00:17 2015] GET /designer/designer_works => generated 11276 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 43/49] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 11:00:17 2015] POST /designer/workd_unexecute => generated 1372 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 44/50] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:00:18 2015] POST /designer/auditing => generated 5062 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 45/51] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 11:00:35 2015] POST /designer/workd_unexecute => generated 1372 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/aa80862af2ad46fb9cfdf06cf640df2e.stl
[pid: 5062|app: 0|req: 46/52] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:00:48 2015] POST /designer/show_3d => generated 60 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 5/53] 192.168.1.108 () {54 vars in 1020 bytes} [Fri Sep 11 11:00:56 2015] POST /designer/screenshot => generated 21 bytes in 81 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5052|app: 0|req: 2/54] 192.168.1.108 () {54 vars in 1020 bytes} [Fri Sep 11 11:00:56 2015] POST /designer/screenshot => generated 21 bytes in 123 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
/usr/local/lib/python2.7/dist-packages/Django-1.8.2-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Goods_Upload.restdate received a naive datetime (2015-09-16 11:00:56.889111) while time zone support is active.
  RuntimeWarning)

[pid: 5063|app: 0|req: 2/55] 192.168.1.108 () {56 vars in 1162 bytes} [Fri Sep 11 11:00:56 2015] POST /designer/edit_submit => generated 0 bytes in 193 msecs (HTTP/1.1 302) 4 headers in 161 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 47/56] 192.168.1.108 () {50 vars in 948 bytes} [Fri Sep 11 11:00:56 2015] GET /designer/designer_works => generated 11277 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 6/57] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 11:00:57 2015] POST /designer/workd_unexecute => generated 874 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 48/58] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:00:57 2015] POST /designer/auditing => generated 5252 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 49/59] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:01:00 2015] POST /designer/auditing => generated 1507 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 50/60] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:01:02 2015] POST /designer/auditing => generated 5252 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 51/61] 192.168.1.108 () {50 vars in 948 bytes} [Fri Sep 11 11:01:07 2015] GET /designer/designer_works => generated 11277 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 7/62] 192.168.1.108 () {56 vars in 1055 bytes} [Fri Sep 11 11:01:08 2015] POST /designer/workd_unexecute => generated 874 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5064|app: 0|req: 8/63] 192.168.1.108 () {54 vars in 1010 bytes} [Fri Sep 11 11:01:10 2015] POST /designer/auditing => generated 5252 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 52/64] 192.168.1.108 () {54 vars in 1024 bytes} [Fri Sep 11 11:01:29 2015] POST /designer/workd_unexecute => generated 874 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 53/65] 192.168.1.108 () {48 vars in 889 bytes} [Fri Sep 11 11:01:34 2015] GET /shop/home => generated 19514 bytes in 25 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 54/66] 192.168.1.108 () {48 vars in 912 bytes} [Fri Sep 11 11:01:36 2015] GET /shop/goods-detail?goods_id=5 => generated 17998 bytes in 101 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 55/67] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 11:01:38 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Fri Sep 11 11:02:07 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8077).
bind(): Address already in use [core/socket.c line 764]
[pid: 5062|app: 0|req: 56/68] 192.168.1.108 () {50 vars in 943 bytes} [Fri Sep 11 11:02:10 2015] GET /shop/goods-detail?goods_id=5 => generated 17998 bytes in 65 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 57/69] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 11:02:11 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 58/70] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 11:03:30 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.10 (64bit) on [Fri Sep 11 11:05:07 2015] ***
compiled with version: 4.8.4 on 17 June 2015 10:52:40
os: Linux-3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
nodename: renjie-B85M-D3H
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/develop/new3d/new_printer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/develop/new3d/new_printer
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30595
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8077).
bind(): Address already in use [core/socket.c line 764]
[pid: 5062|app: 0|req: 59/71] 192.168.1.108 () {50 vars in 943 bytes} [Fri Sep 11 11:05:10 2015] GET /shop/goods-detail?goods_id=5 => generated 17998 bytes in 85 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 60/72] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 11:05:14 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 5062|app: 0|req: 61/73] 192.168.1.108 () {50 vars in 943 bytes} [Fri Sep 11 11:05:56 2015] GET /shop/goods-detail?goods_id=5 => generated 17998 bytes in 94 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
/static/59bfd639738b706bb10eecdd800195ea.stl
[pid: 5062|app: 0|req: 62/74] 192.168.1.108 () {54 vars in 1015 bytes} [Fri Sep 11 11:05:58 2015] POST /designer/show_3d => generated 60 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
